export const MOBILE_BREAKPOINT = 768

export const TOAST = {
  LIMIT: 1,
  REMOVE_DELAY: 1000000
} as const

export const ACTION_TYPES = {
  ADD_TOAST: "ADD_TOAST",
  UPDATE_TOAST: "UPDATE_TOAST",
  DISMISS_TOAST: "DISMISS_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST"
} as const 